image: ubuntu

services:
- docker

environment:
  global:
    LOCAL_DOCKER_IMAGE: "local/builder:latest"
  matrix:
    - TARGET_NAME: "rpi"
    - TARGET_NAME: "rpi_one"
    - TARGET_NAME: "rpi_one_openblas"
    - TARGET_NAME: "odroidc1"
    - TARGET_NAME: "odroidc2"
    - TARGET_NAME: "beagle_black"

install:
- pushd build_tensorflow
- docker build -t $LOCAL_DOCKER_IMAGE -f Dockerfile .
- popd
- mkdir -p $TARGET_NAME

build: off

test_script:
- docker run -v $APPVEYOR_BUILD_FOLDER/$TARGET_NAME:/tmp $LOCAL_DOCKER_IMAGE /root/build_tensorflow.sh /root/configs/$TARGET_NAME.conf
